### PR TITLE
Added connection pool

### PR DESCRIPTION
**Pull request by mmoreram**

### CODE REVIEW

**Comment by mmoreram** [comment]
Hello @marinhekman 

Thanks for the comment and for using the project. I'm glad seeing that the project is useful :)
Sorry for leaving this PR on standby. Of course. If you can test this branch to see what's the behavior on "real" projects, I will do the same with mine (@apisearch-io), and if everything runs as expected, then, I will merge and tag the package.

**Comment by marinhekman** [comment]
@mmoreram perfect. I will let you know within a couple of weeks

**Comment by marinhekman** [comment]
@mmoreram I succesfullly tested with 40 connections. Basically replaced 
`Connection::createConnected` with `ConnectionPool::createConnected` and added the number of connections to the Credentials constructor call.

Question: how would you handle a mysql idle timeout? 
Since I am running a websocket server, and without any activity for like 8 hours, the connection would break.
With a single connection I could just do a dummy query to "prevent" the time-out like this:
```
        // do a dummy SELECT 1 query every 4 hours to prevent the "wait_timeout" of mysql (Default is 8 hours).
        //  if the wait timeout would go off, the database connection will be broken, and the error
        //  "2006 MySQL server has gone away" will appear.
        $loop->addPeriodicTimer(14400, function () {
            $qb = $this->connection->createQueryBuilder();
            $this->connection->query(
                $qb->select('1')
            );
        }
```
Of course with a pool I would have to traverse each of one the connections...not the best solution, and I not even sure I can traverse each connection now.

Maybe there a way to just handle the "2006 MySQL server has gone away" exception and do a re-connection ? I can probably handle the exception in the rejection of the promise, but how do I tell Drift PHP to do a re-connection?

**Comment by marinhekman** [comment]
@mmoreram it would be handy to have a way to iterate over the connections in the pool.

**Comment by marinhekman** [comment]
I did this for now: https://github.com/marinhekman/reactphp-dbal/commit/c4f1a4059e48eac0b8508394da5c1d7d4929c7e9

**Comment by mmoreram** [comment]
Hello!

Thanks for your work :) I really appreciate it.
I'm thinking about this new `ping` strategy to keep connections up and running, and to be honest, it's perfect. I think that I'm having some similar issues in some of my projects, and that would solve them as well.

I'm thinking then.
Why don't we add this logic inside the connection pool?
Seems a good move to return all workers, but we could explore this, and even add in the library the `keep-alive` strategy.

**Comment by mmoreram** [comment]
@marinhekman I'm mergin both your PR and mine, and will add a minor release for you to start using it on prod.

If you want to explore the addition of this keep alive inside the library, that would be awesome.
My 5 cents.

- Add a `keep_alive_each` or similar parameter inside the new connection creation method
- If this is defined, then add the loop periodic timer
- If the connection is closed, detach this timer
- If we have a connection pool, do the same but with all timers

**Comment by marinhekman** [comment]
@mmoreram thanks . I will explore the addition of keep_alive_each suggestion in my fork and let you know.

**Pull request merged**
